# Generated by Django 5.2.4 on 2025-08-29 14:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('VCB', 'Vietcombank'), ('TCB', 'Techcombank'), ('BIDV', 'BIDV'), ('ACB', 'ACB'), ('MB', 'MB Bank'), ('VPB', 'VPBank'), ('AGB', 'Agribank'), ('SCB', 'Sacombank'), ('TPB', 'TPBank'), ('VIB', 'VIB'), ('OCB', 'OCB'), ('MSB', 'MSB'), ('HDB', 'HDBank'), ('SHB', 'SHB'), ('STB', 'Sacombank')], max_length=50)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('account_holder', models.CharField(max_length=200)),
                ('branch', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tài khoản ngân hàng',
                'verbose_name_plural': 'Tài khoản ngân hàng',
                'ordering': ['bank_name', 'account_number'],
            },
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Rạp chiếu phim',
                'verbose_name_plural': 'Rạp chiếu phim',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Thể loại phim',
                'verbose_name_plural': 'Thể loại phim',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('available', 'Còn trống'), ('booked', 'Đã đặt'), ('reserved', 'Đã giữ')], default='available', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Ghế',
                'verbose_name_plural': 'Ghế',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('processing', 'Đang xử lý thanh toán'), ('paid', 'Đã thanh toán'), ('cancelled', 'Đã hủy'), ('expired', 'Hết hạn'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20)),
                ('booking_status', models.CharField(choices=[('confirmed', 'Đã xác nhận'), ('pending', 'Chờ xác nhận'), ('cancelled', 'Đã hủy'), ('completed', 'Đã hoàn thành')], default='pending', max_length=20)),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Thời hạn thanh toán', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('seats', models.ManyToManyField(related_name='bookings', to='booking.seat')),
            ],
            options={
                'verbose_name': 'Đặt vé',
                'verbose_name_plural': 'Đặt vé',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(help_text='Thời lượng phim (phút)')),
                ('release_date', models.DateField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('trailer_url', models.URLField(blank=True, help_text='URL video YouTube (cũ)', null=True)),
                ('video_file', models.FileField(blank=True, help_text='File video trailer (MP4, WebM, OGV)', null=True, upload_to='videos/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_hot', models.BooleanField(default=False, help_text='Phim đang hot')),
                ('views_count', models.IntegerField(default=0, help_text='Số lượt xem')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='booking.genre')),
            ],
            options={
                'verbose_name': 'Phim',
                'verbose_name_plural': 'Phim',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Tiền mặt'), ('bank_transfer', 'Chuyển khoản ngân hàng'), ('credit_card', 'Thẻ tín dụng'), ('momo', 'Ví MoMo'), ('zalopay', 'Ví ZaloPay'), ('vnpay', 'VNPay')], default='cash', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại'), ('cancelled', 'Đã hủy'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Mã giao dịch từ cổng thanh toán', max_length=100, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('sender_account', models.CharField(blank=True, help_text='Số tài khoản người gửi', max_length=20, null=True)),
                ('sender_name', models.CharField(blank=True, help_text='Tên người gửi', max_length=200, null=True)),
                ('transfer_content', models.CharField(blank=True, help_text='Nội dung chuyển khoản', max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Số điện thoại MoMo', max_length=15, null=True)),
                ('card_number', models.CharField(blank=True, help_text='Số thẻ VNPay', max_length=20, null=True)),
                ('card_holder', models.CharField(blank=True, help_text='Tên chủ thẻ VNPay', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, help_text='Tài khoản ngân hàng được chọn', null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.bankaccount')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='booking.booking')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='booking.cinema')),
            ],
            options={
                'verbose_name': 'Phòng chiếu',
                'verbose_name_plural': 'Phòng chiếu',
            },
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_times', to='booking.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_times', to='booking.screen')),
            ],
            options={
                'verbose_name': 'Suất chiếu',
                'verbose_name_plural': 'Suất chiếu',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='show_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking.showtime'),
        ),
        migrations.AddField(
            model_name='booking',
            name='show_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.showtime'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('customer', 'Khách hàng'), ('staff', 'Nhân viên'), ('admin', 'Quản trị viên')], default='customer', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ người dùng',
                'verbose_name_plural': 'Hồ sơ người dùng',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='booking.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'movie')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('show_time', 'seat_number')},
        ),
    ]
